version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      deps:
        patterns:
          - "*"
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      deps:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major","version-update:semver-minor"]
