version: '3.7'

services:
  paulweb:
    image: serverlein/paulweb:latest
    restart: always
    networks:
      traefik-public:
    deploy:
      update_config:
        parallelism: 2
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.paul-roloff.rule=Host(`paul-roloff.de`)"
        - "traefik.http.routers.paul-roloff.entrypoints=websecure"
        - "traefik.http.routers.paul-roloff.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.paul-roloff.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true
